### ISSUE TITLE
isDevice16bit() is not work if ReScanBus happen.

### ISSUE THREAD

**Issue by yungsheng** [openbmc/entity-manager#20]
I do ReScanBus and sometimes isDevice16bit() will detect M24C64 as 8bit EEPROM.
When ReScanBus called, the address pointer of M24C64 is not move to first address. 
And it fail to detect M24C64 is 16bit EEPROM.

**Comment by jaehyoo** [comment]
The addressing type detection logic can't cover all cases because it uses
non-invasive way to prevent any actual data writing on uncertain eeproms.
In case the logic doesn't work and if your eeprom is at fixed address in a
specific bus, add the eeprom node into device tree explicitely as an
alternative way.

-Jae

**Comment by Yung-sheng** [comment]
Ok, I see.
Thank you.
